"""
corpus_map.py — Build a line-addressed map of the Bruno/Llull corpus.

Serves PROGRESSIVE REVELATION (PROMPTS.md P-10): a session should read a
*slice* of a source, never a whole file. This emits docs/CORPUS_MAP.md with
file -> line -> heading, so any task can jump straight to the relevant range:

    sed -n '1288,1400p' "<file>"

Idempotent. Re-run whenever the corpus changes.

Usage:
    python scripts/corpus_map.py [--corpus DIR] [--min-heads N]
"""

import re
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DEFAULT_CORPUS = Path(r"E:\pdf\renaissance magic\Bruno Lull\plain_text_drafts")
OUT_PATH = BASE_DIR / "docs" / "CORPUS_MAP.md"

# Section openers that matter for an art-of-memory / practice hunt.
# Ordered by usefulness; used to flag lines as HIGH-VALUE in the map.
PRACTICE_SIGNALS = [
    'atri', 'locus', 'loci', 'place', 'image', 'imagin', 'memor', 'mnemo',
    'statue', 'seal', 'sigil', 'wheel', 'rota', 'figure', 'alphabet',
    'chamber', 'subject', 'adjective', 'substantive', 'species', 'sign',
]

HEADING_RE = re.compile(
    r'^(?:'
    r'(?:Book|Part|Chapter|Article|Section|Prologue|Epilogue|Appendix)\b.*'
    r'|(?:On|Of|Concerning|Regarding|The|A)\s+[A-Za-z].{3,70}'
    r'|[A-Z][A-Za-z\'\- ]{4,60}'
    r')$'
)


def looks_like_heading(line: str) -> bool:
    s = line.strip()
    if not (5 <= len(s) <= 90):
        return False
    if s.endswith(('.', ',', ';', ':', '?', '!')):
        return False
    if not HEADING_RE.match(s):
        return False
    # Reject lines that are mostly lowercase prose fragments
    words = s.split()
    if len(words) < 2 or len(words) > 12:
        return False
    caps = sum(1 for w in words if w[:1].isupper())
    return caps / len(words) >= 0.4


def is_high_value(heading: str) -> bool:
    h = heading.lower()
    return any(sig in h for sig in PRACTICE_SIGNALS)


def map_file(path: Path):
    """Return (n_lines, [(lineno, heading, high_value), ...])."""
    heads = []
    try:
        lines = path.read_text(encoding='utf-8', errors='replace').splitlines()
    except OSError as e:
        print(f"  ! could not read {path.name}: {e}")
        return 0, []
    for i, line in enumerate(lines, start=1):
        if looks_like_heading(line):
            h = line.strip()
            heads.append((i, h, is_high_value(h)))
    return len(lines), heads


def main():
    corpus = DEFAULT_CORPUS
    args = sys.argv[1:]
    if '--corpus' in args:
        corpus = Path(args[args.index('--corpus') + 1])

    if not corpus.exists():
        print(f"ERROR: corpus not found: {corpus}")
        print("Pass --corpus DIR if it has moved.")
        return 1

    files = sorted(corpus.glob('*.txt'))
    if not files:
        print(f"ERROR: no .txt files in {corpus}")
        return 1

    out = [
        "# CORPUS MAP",
        "",
        "**Generated by `scripts/corpus_map.py`. Do not hand-edit — re-run instead.**",
        "",
        f"Corpus: `{corpus}`  ",
        f"{len(files)} plain-text sources (pre-extracted; PDFs alongside them).",
        "",
        "## How to use this (progressive revelation — PROMPTS.md P-10)",
        "",
        "Read a **slice**, never a whole file. These sources run 5k–15k lines.",
        "",
        "```bash",
        'cd "' + str(corpus) + '"',
        "sed -n '1288,1400p' \"<filename>\"      # read one section",
        "grep -n \"atrium\" \"<filename>\" | head   # locate before reading",
        "```",
        "",
        "★ marks headings matching practice-relevant signals "
        "(loci, images, atria, statues, seals, wheels, species…) — "
        "the first places to look when mining for playable material.",
        "",
        "---",
        "",
    ]

    total_heads = 0
    for f in files:
        n_lines, heads = map_file(f)
        if n_lines == 0:
            continue
        hv = [h for h in heads if h[2]]
        total_heads += len(heads)

        out.append(f"## {f.name}")
        out.append("")
        out.append(f"`{n_lines:,}` lines · `{len(heads)}` headings detected · "
                   f"`{len(hv)}` practice-relevant")
        out.append("")

        if not heads:
            out.append("_No headings detected — likely continuous prose. "
                       "Use `grep -n` to locate material._")
            out.append("")
            continue

        # Show high-value headings first, then a capped full list.
        if hv:
            out.append("**★ Practice-relevant sections**")
            out.append("")
            out.append("| line | heading |")
            out.append("|---:|---|")
            for lineno, h, _ in hv[:40]:
                out.append(f"| {lineno} | ★ {h} |")
            out.append("")

        shown = heads[:60]
        out.append(f"<details><summary>All detected headings "
                   f"({len(shown)} of {len(heads)} shown)</summary>")
        out.append("")
        out.append("| line | heading |")
        out.append("|---:|---|")
        for lineno, h, high in shown:
            mark = "★ " if high else ""
            out.append(f"| {lineno} | {mark}{h} |")
        out.append("")
        out.append("</details>")
        out.append("")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(out), encoding='utf-8')

    print(f"Wrote {OUT_PATH}")
    print(f"  {len(files)} files, {total_heads} headings detected")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
